"""I have changed the name RegNo to regnowq

Revision ID: 089e5ddec740
Revises: c40dd922d1b3
Create Date: 2023-06-09 17:02:40.096426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '089e5ddec740'
down_revision = 'c40dd922d1b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('regno', sa.String(length=64), nullable=True))
        batch_op.create_unique_constraint('uq_users_regno', ['regno'])
        batch_op.drop_column('RegNumber')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('RegNumber', sa.VARCHAR(length=64), nullable=True))
        batch_op.drop_constraint('uq_users_regno', type_='unique')
        batch_op.drop_column('regno')

    # ### end Alembic commands ###
