"""new books table

Revision ID: 45d39a5ca1a3
Revises: a5a410ffc9df
Create Date: 2023-06-15 09:44:13.026043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45d39a5ca1a3'
down_revision = 'a5a410ffc9df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('author', sa.String(length=64), nullable=True),
    sa.Column('isbn', sa.String(length=64), nullable=True),
    sa.Column('publisher', sa.String(length=64), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('genre', sa.String(length=64), nullable=True),
    sa.Column('condition', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isbn')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_email')
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_index('ix_users_email', ['email'], unique=False)

    op.drop_table('books')
    # ### end Alembic commands ###
