"""added a password field

Revision ID: a5a410ffc9df
Revises: 7304a6d8401a
Create Date: 2023-06-12 10:17:33.100235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5a410ffc9df'
down_revision = '7304a6d8401a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('IDno', sa.String(length=64), nullable=True))
        batch_op.drop_constraint('uq_users_regno', type_='unique')
        batch_op.create_unique_constraint('add_IDno', ['IDno'])
        batch_op.create_unique_constraint('add_password', ['password'])
        batch_op.drop_column('regno')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('regno', sa.VARCHAR(length=64), nullable=True))
        batch_op.drop_constraint('remove_regno', type_='unique')
        batch_op.drop_constraint('remove_regno', type_='unique')
        batch_op.create_unique_constraint('uq_users_regno', ['regno'])
        batch_op.drop_column('IDno')
        batch_op.drop_column('password')

    # ### end Alembic commands ###
